version: '3.3'

services: 

  script:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    command: python3 /opt/service/summarize.py -model local-bert-large-uncased -num-sentences 5 -path /opt/example.txt
    volumes:
      - ./models:/opt/models:ro
      - ./summarize.py:/opt/service/summarize.py:ro
      - ./summarizer:/opt/service/summarizer:ro
      - ./example.txt:/opt/example.txt:ro
